"""
Django settings for threadit project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-yz4%$d!bb0z$p@2_&%_8+p7!hudnn2ub@gez*01j@!5%m63)c1')


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'core',  # newly added app for main 'core' logic
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'threadit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'threadit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# This is the "production switch" for your database.
# It looks for the Neon database URL in Render's "key safe".
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # If it finds the Neon key, it uses dj-database-url (the "translator")
    # to configure your live PostgreSQL database.
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=True
    )

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------
# AUTHENTICATION REDIRECTS
# ----------------------------------------------

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login' # written for the redirection used by the login_required decorator of posting functionality.

# --- STATIC FILES CONFIGURATION ---
# This is the URL path where Django will *serve* static files from.
# e.g., http://example.com/static/css/style.css
STATIC_URL = 'static/'

# This tells Django to look for a folder named "static"
# in the main project directory.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# --- MEDIA FILES (User Uploaded) CONFIGURATION ---

# 1. MEDIA_URL: The public-facing URL for media files.
#    Just like STATIC_URL, this is the web address browsers will use
#    to request user-uploaded images (e.g., /media/post_images/my_image.jpg).
MEDIA_URL = '/media/'

# 2. MEDIA_ROOT: The private folder on your computer's hard drive
#    where Django will *actually save* all user-uploaded files.
#    BASE_DIR / 'media' tells Django to create a folder named "media"
#    in your main project directory (alongside 'static' and 'core').
MEDIA_ROOT = BASE_DIR / 'media'

# This automatically finds your live app's URL (e.g., threadit-app.onrender.com)
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# We also add 'localhost' so you can still work on your laptop
ALLOWED_HOSTS.append('127.0.0.1')

# --- ADD THIS LINE (This is the fix for your error) ---
# This is the "Shipping Crate" folder.
# 'collectstatic' will copy all CSS/JS files into this one folder
# for the production server (gunicorn) to use.
STATIC_ROOT = BASE_DIR / 'staticfiles'